[editor]
cursorline = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.lsp]
display-messages = true

[editor.whitespace.characters]
space = " "
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"
