[[language]]

name = "python"
language-servers = [ "basedpyright", "ruff" ]

[language-server.basedpyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = ["server"]
