wtf:
  colors:
    border:
      normal: "cornsilk"
      focusable: "cornsilk"
      focused: "cadetblue"
    checked: "gray"
    highlight:
      fore: "black"
      back: "green"
    text: "white"
    title: "white"
  grid:
    columns: [10, 10, 10, 10, 10, 10, 10, 10]
    rows:    [10, 10, 10, 10, 10, 10, 10, 10]
  refreshInterval: 1
  mods:
    prettyweather:
      enabled: true
      city: "philadelphia"
      position:
        top: 0
        left: 0
        height: 1
        width: 6
      refreshInterval: 1200
      unit: "u"
      view: 0
      language: "en"

    github:
      baseURL: ""
      customQueries:
        prism:
          title: "Prism"
          filter: "repo:BenefitsDataTrust/prism is:open is:pr sort:updated-desc"
      enabled: true
      enableStatus: true
      position:
        top: 1
        left: 0
        height: 5
        width: 6
      refreshInterval: 300
      repositories:
        - "BenefitsDataTrust/prism"
      uploadURL: ""
      username: "rthoward"

    gcal:
      colors:
        title: "cornsilk"
        eventTime: "cornsilk"
        description: "cornsilk"
        past: "linen"
      calendarReadLevel: "reader"
      conflictIcon: "🚨"
      currentIcon: "💥"
      displayResponseStatus: true
      email: "richard@promptworks.com"
      enabled: true
      eventCount: 15
      hourFormat: "12"
      multiCalendar: false
      position:
        top: 0
        left: 6
        height: 5
        width: 5
      refreshInterval: 600
      secretFile: "~/.config/wtf/gcal_credentials.json"
      showDeclined: true
      timezone: "America/New_York"
      withLocation: true
